Implement live packet feed
iarivas/CS4311_CANBusVisualizer_Team_6 pull request #74
Opened 2022-11-20 19:49 UTC by mgmolina3

2022-11-21 16:00 UTC, matchagreen approved these changes

2022-11-21 17:37 UTC, iarivas approved these changes
LGTM!

2022-11-22 20:09 UTC, iarivas requested changes
Change "_id": projectID -> "eventName": projectID

2022-11-22 21:33 UTC, iarivas approved these changes

2022-11-23 22:49 UTC, merged